import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SignUp from './signup'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Assigned Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.box} >
          <div className={styles.signup}>
            <Link style={{ color: "white" }} href="/signup">Signup</Link>
          </div>
          <div className={styles.login}>
            <Link style={{ color: "white" }} href="/login">Login</Link>
          </div>
        </div>
      </main>
    </>
  )
}
